### ISSUE TITLE
GPO wish: dom.forms.datetime preference

### ISSUE THREAD

**Issue by jwalawski** [mozilla/policy-templates#572] opened 2020-04-09 10:07 UTC
Is it possible to add "dom.forms.datetime" preference to policies? I have intranet app that requires that preference set to "false".

**Comment by mkaply** [comment] 2020-04-09 16:55
I'm curious as to what exactly the issue is? We've had those new datetime forms for a long time.

Have y'all been setting that pref for a couple years?

**Comment by jwalawski** [comment] 2020-04-09 21:09
Up until recently we used only Internet Explorer. The app was updated and it was supposed to be compatible with other browsers.

Setting "dom.forms.datetime" to "false" is necessary for date picker to work correctly, at least for now. Without that there is an error as if no date has been chosen.

**Comment by miketaylr** [comment] 2020-04-09 21:13
@jwalawski if you can share, do you know what framework or library (and what version) is providing a custom date picker that's broken in firefox without this pref disabled?

**Comment by jwalawski** [comment] 2020-04-10 20:52
Date picker is provided by jQuery / jQuery UI v1.12. Date format is set to "dd-mm-yy".

I suppose it might help to change input from date to text and/or change supported date format to "yy-mm-dd". But for now the pref change is the only solution I can use.

**Comment by mkaply** [comment] 2020-09-21 19:24
This is settable via our new Preferences policy which will be released tomorrow.

https://github.com/mozilla/policy-templates#preferences

**Closed by mkaply** 2020-09-21 19:24 UTC
