### ISSUE TITLE
Issue: Bookmarks don't update?

### ISSUE THREAD

**Issue by pouchm** [mozilla/policy-templates#279] opened 2018-10-19 17:16 UTC
I updated a previous policy where I change the Title and URL of a bookmark. The bookmarks do not update until I manually delete the bookmark folder. After that it updates correctly. So it doesn't seem to overwrite the previous bookmarks.

Running Firefox 60.2.2esr x64
Firefox Policies 1.3

Also, GPOwish, is there a way to lock the bookmarks from being deleted by an end user?

**Comment by jeffreymcclain** [comment] 2018-10-23 18:32
I have noticed this issue as well since the v1.0 policy release, I'm not sure if it's a bug or by design. I've also just been deleting the bookmarks folder manually to force it to update, but since most users probably won't bother with this step it should ideally be overwritten automatically.

**Comment by mkaply** [comment] 2018-11-04 14:12
Unfortunately they bookmarks situation is really painful. I'm considering adding a new policy similar to Chrome that just does a Managed Bookmarks folder that always come back no matter what.

**Comment by jeffreymcclain** [comment] 2018-11-04 18:53
> Unfortunately they bookmarks situation is really painful. I'm considering adding a new policy similar to Chrome that just does a Managed Bookmarks folder that always come back no matter what.

I would prefer this approach as well, I recently had a meeting with my coworkers and their main desire was for me to "replicate Chrome's Managed Bookmark functionality in Firefox as closely as possible". Hopefully mirroring Chrome's approach would also fix the bug of group policy bookmarks not populating if they already exist somewhere else (might be the same bug as described above or at least related, idk). 

Example: If a bookmark to https://www.google.com already exists in the Menu area, and I use the group policy to add a bookmark to the same URL in the toolbar, the group policy does nothing until the Menu bar bookmark is deleted.

**Comment by pouchm** [comment] 2018-11-05 14:06
> Unfortunately they bookmarks situation is really painful. I'm considering adding a new policy similar to Chrome that just does a Managed Bookmarks folder that always come back no matter what.

Sorry to hear about all the issues regarding bookmarks! As a person that manages 4 browsers (IE, Chrome, FF, Edge) I will say the Chrome implementation of bookmarks works the most reliably and is the easiest to manage.

Thanks for all your work! I appreciate to response!

**Comment by aschaeffer323** [comment] 2019-05-20 11:38
I know this is old but is there any update on this as I to am trying to change a bookmark but it is not updating on the clients end. I delete it and it comes back as the old. Change the bookmark location to Bookmark 6 and it shows both.

**Comment by stroodle96** [comment] 2020-10-06 14:54
Having the same issues.  Any updates?

**Comment by mkaply** [comment] 2020-10-06 15:33
Unfortunately our bookmark implementation just wasn't great.

I've implemented ManagedBookmarks exactly like Chrome and they will be in the next Firefox/ESR update in a couple weeks.

**Comment by mkaply** [comment] 2020-11-17 21:31
Managed bookmarks is now available.

https://github.com/mozilla/policy-templates/blob/master/README.md#managedbookmarks

**Closed by mkaply** 2020-11-17 21:31 UTC
