### ISSUE TITLE
allow setting to update firefox to a prefix, granular control

### ISSUE THREAD

**Issue by googol13** [mozilla/policy-templates#526] opened 2020-02-05 20:28 UTC
dont necessarily want to have automatically go to the latest without some control, but like Chrome, you can set a prefix

for example, if you set it to 72, it would allow all builds and versions of 72.x.x

setting 72, would permit 72.0.1, 72.0.2, 72.1, etc for firefox to auto update

right now the only update policy we can have is disable updating entirely, which is never good too.

Hope you can implement this policy setting and into firefox build

Cheers

**Comment by kedia990** [comment] 2020-04-06 23:56
Duplicate of #328

**Comment by mkaply** [comment] 2022-04-22 18:26
This is being worked on in Firefox

https://bugzilla.mozilla.org/show_bug.cgi?id=1529943

**Closed by mkaply** 2022-04-22 18:26 UTC
